# Generated by Django 4.1.6 on 2023-05-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("ACCEPTED", "Accepted"),
                            ("SUBMITTED", "Submitted"),
                            ("DELIVERED", "Delivered"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("price", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("required_at", models.DateTimeField(auto_now=True)),
                ("shipped_date", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_worker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_worker_orders",
                        to="accounts.deliveryworker",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="doctor_orders", to="accounts.doctor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=1)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="order_set", to="order.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_set",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(through="order.OrderProduct", to="product.product"),
        ),
    ]
