# Generated by Django 4.1.3 on 2022-11-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_price_alter_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="discount", field=models.FloatField(default=0),
        ),
    ]
