# Generated by Django 4.1.3 on 2022-11-29 15:12

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=product.models.upload_to
            ),
        ),
    ]
