# Generated by Django 4.1.3 on 2022-11-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_service_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="warehouse",
            field=models.ManyToManyField(to="accounts.warehouseprofile"),
        ),
        migrations.AlterField(
            model_name="service",
            name="Warehouse",
            field=models.ManyToManyField(to="accounts.warehouseaccountant"),
        ),
    ]
