# Generated by Django 4.1.3 on 2022-11-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_section_warehouse_alter_service_warehouse"),
    ]

    operations = [
        migrations.RemoveField(model_name="warehouseprofile", name="sections",),
        migrations.RemoveField(model_name="warehouseprofile", name="service",),
        migrations.AlterField(
            model_name="section",
            name="warehouse",
            field=models.ManyToManyField(
                related_name="sections", to="accounts.warehouseprofile"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="Warehouse",
            field=models.ManyToManyField(
                related_name="services", to="accounts.warehouseaccountant"
            ),
        ),
    ]
