# Generated by Django 4.1.3 on 2022-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_warehouseprofile_sections_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="Warehouse",
            field=models.ManyToManyField(
                related_name="services", to="accounts.warehouseprofile"
            ),
        ),
    ]
