# Generated by Django 4.1.3 on 2022-11-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_service_warehouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Doctor", "doctor"),
                    ("Delivery worker", "delivery worker"),
                    ("Warehouse", "warehouse"),
                    ("Admin", "admin"),
                    ("Statistician", "statistician"),
                    ("Base accountant", "base accountant"),
                    ("Delivery worker accountant", "delivery worker accountant"),
                    ("Warehouse accountant", "warehouse accountant"),
                ],
                default="Admin",
                max_length=50,
            ),
        ),
    ]
