# Generated by Django 4.1.3 on 2023-01-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryworkerprofile",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.subscription",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.subscription",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warehouseprofile",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.subscription",
            ),
            preserve_default=False,
        ),
    ]
