# Generated by Django 4.1.3 on 2023-01-18 09:07

import accounts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_deliveryworkerprofile_subscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryworkerprofile",
            name="first_name",
            field=models.CharField(
                max_length=200, validators=[accounts.validators.NameRegexValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="deliveryworkerprofile",
            name="last_name",
            field=models.CharField(
                max_length=200, validators=[accounts.validators.NameRegexValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="first_name",
            field=models.CharField(
                max_length=200, validators=[accounts.validators.NameRegexValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="last_name",
            field=models.CharField(
                max_length=200, validators=[accounts.validators.NameRegexValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseprofile",
            name="name",
            field=models.CharField(
                max_length=200, validators=[accounts.validators.NameRegexValidator()]
            ),
        ),
    ]
