# Generated by Django 4.1.5 on 2023-01-20 10:08

import accounts.models_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_deliveryworkerprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.models_manager.CustomUserManager()),
            ],
        ),
    ]
