# Generated by Django 4.1.6 on 2023-05-12 16:49

import apps.product.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("price", models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ("quantity", models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("discount", models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("image", models.ImageField(blank=True, null=True, upload_to=apps.product.models.upload_to)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("visible", models.BooleanField(default=True)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="products", to="accounts.warehouse"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "warehouse")},
            },
        ),
    ]
