# Generated by Django 4.1.3 on 2022-11-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="accepted",),
        migrations.RemoveField(model_name="order", name="delivered",),
        migrations.RemoveField(model_name="order", name="rejected",),
        migrations.RemoveField(model_name="order", name="submitted",),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("ACCEPTED", "Accepted"),
                    ("SUBMITTED", "Submitted"),
                    ("DELIVERED", "delivered"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
    ]
