# Generated by Django 4.1.3 on 2022-11-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_accepted_remove_order_delivered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("ACCEPTED", "Accepted"),
                    ("SUBMITTED", "Submitted"),
                    ("DELIVERED", "Delivered"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
    ]
