# Generated by Django 4.1.3 on 2022-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_price_alter_product_quantity"),
        ("order", "0003_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="items",),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                through="order.OrderProduct", to="product.product"
            ),
        ),
    ]
