# Generated by Django 4.1.3 on 2022-11-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_order_items_order_products"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderproduct", name="discount",),
    ]
